# Configuration for https://travis-ci.org/

dist: bionic

language: c

compiler:
    - gcc
    - clang

addons:
    apt:
        packages:
            - coreutils
            - python-dev
            - python3-dev

script:
    - make test


